name = "Aman El-Mandoob"
client_id = "8eda1fbf54512f4816ea053993f0190"
application_url = "https://ahmednoaman.pythonanywhere.com/"
privacy_policy_url = "https://ahmednoaman.pythonanywhere.com/privacy"

[access_scopes]
scopes = "read_orders,write_orders,read_products"

[auth]
redirect_urls = [
"https://ahmednoaman.pythonanywhere.com/auth/callback"
]
