name = "Aman El-Mandoob"
client_id = "YOUR_CLIENT_ID"
application_url = "https://ahmdnoaman.pythonanywhere.com/"
privacy_policy_url = "https://ahmdnoaman.pythonanywhere.com/privacy"

[access_scopes]
scopes = "read_orders,write_orders,read_products"

[auth]
redirect_urls = [
  "https://ahmdnoaman.pythonanywhere.com/auth/callback"
]
